from clippd_info import get_clipped_info
from shot_distance import get_distance_coord
from shot_distance import get_shot_type_info
from shot_miss import get_shot_miss_info
from strokes_gained import get_strokes_gained_info

from utils import read_excel_file


def sort_data(arccos_data):
    """Sort data using  by specific fields"""

    arccos_data.sort_values(
        by=["round_userId", "round_startTime", "roundId", "hole_holeId", "shot_shotId"],
        inplace=True,
    )
    return arccos_data


def last_sort(arccos_data):
    # Add Clippd dataframe to data
    # Sort.
    arccos_data.sort_values(
        by=["player_id", "round_time", "round_id", "hole_id", "shot_id"], inplace=True
    )
    return arccos_data


def fill_na(arccos_data):
    arccos_data["shot_startTerrain"] = arccos_data["shot_startTerrain"].fillna("Green")
    arccos_data["shot_endTerrain"] = arccos_data["shot_endTerrain"].fillna("Green")
    return arccos_data


def mapping(arccos_data, data_mapping_dict_file):
    data_dictionary = read_excel_file(data_mapping_dict_file)
    arccos_data_dictionary = data_dictionary[["Clippd", "Arccos"]]
    arccos_data_dictionary = (
        arccos_data_dictionary.dropna().set_index("Arccos").to_dict()["Clippd"]
    )
    filtered_columns = list(arccos_data_dictionary.keys())
    filtered_columns.remove("'arccos'")
    arccos_data = arccos_data[filtered_columns].copy()
    arccos_data.columns = arccos_data.columns.to_series().map(
        arccos_data_dictionary
    )  # TODO: fix
    arccos_data["data_source"] = "arccos"
    return arccos_data


def process_fields(arccos_data):
    """process field by fixing the values"""

    # Process the dataframe  generated by convert raw
    arccos_data = arccos_data.fill_na(arccos_data)

    # Capitalize first letter of string
    arccos_data[["shot_startTerrain", "shot_endTerrain"]] = arccos_data[
        ["shot_startTerrain", "shot_endTerrain"]
    ].apply(lambda s: s.capitalize())

    arccos_data = get_distance_coord(arccos_data)
    arccos_data = get_shot_type_info(arccos_data)
    arccos_data = get_shot_miss_info(arccos_data)
    arccos_data = get_strokes_gained_info(
        arccos_data, "PGA Benchmark.csv", "PGA Putting Benchmark.csv"
    )
    arccos_data = mapping(arccos_data)
    arccos_data = get_clipped_info(arccos_data, "data_dictionary.xlsx")

    return arccos_data
